apiVersion: v1
kind: Namespace
metadata:
  name: hung-argocd1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-argocd
  namespace: hung-argocd1
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/daohung01/argocd-push-code.git
    targetRevision: master
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
